### ISSUE TITLE
Need way to tell aardvark DNS to refer to a particular DNS, and not host's configured DNS

### ISSUE THREAD

**Issue by dshenai** [containers/aardvark-dns#228]
This is a request for enhancement.

Currently aardvark DNS resolves container names and for anything it can not resolve on its own, it refers to the configured resolvers on the host. Requirement is that: Need a way to tell aardvark DNS to refer to a particular DNS, and not host's configured DNS. This is because I need host to work on separate DNS and container to work on separate DNS.

I tried doing this by bind mounting a alternate_resolve.conf from host to container. It has 2 entries. First is of aardvark DNS and my second is of alternate DNS (say DNS1). Now, note that, my host has DNS2 in its resolv.conf. 
Expected behavior:
For FQDNs that aardvark DNS can not resolve, my expectation is that the forward request should go to DNS1. 
Observed behavior:
Instead, it goes to DNS2.

Kindly guide to understand if this is a valid requirement.
Also, as this is not working currently, is there a workaround to make it work?

Thank you

**Comment by flouthoc** [comment]
Hi @dshenai , Thanks for creating the issue.

As of now users don't directly configure aardvark-dns and not sure if there is a plan to provide any direct configuration. But I think a config via `containers.conf` can be opened up and podman can thus convey aardvark which resolver to use and by default it can keep using host's resolver.

Tagging other maintainers for their opinion on this @Luap99 @mheon @baude WDYT ?

**Comment by mheon** [comment]
We do not use the host's DNS, but the container's DNS, which defaults to the same nameservers as the host. Setting container default DNS servers in containers.conf ought to do what you want.

**Comment by flouthoc** [comment]
Okay its already there, see field `dns_servers` here: https://github.com/containers/common/blob/main/docs/containers.conf.5.md

**Comment by Luap99** [comment]
> We do not use the host's DNS, but the container's DNS, which defaults to the same nameservers as the host. Setting container default DNS servers in containers.conf ought to do what you want.

I don't think this is true, aardvark-dns has no access to the containers dns servers so it just uses the host /etc/resolv.conf as upstream servers: https://github.com/containers/aardvark-dns/blob/d77ecad2a9ca4ca8ad66d380f702928869882d87/src/dns/coredns.rs#L70

**Comment by mheon** [comment]
...Did we not implement that yet? Because that was definitely in the original design doc.

**Comment by mheon** [comment]
Well, we have a session later today about new functionality, we can add this to it.

**Comment by dshenai** [comment]
Thank you for your quick responses.
Is it possible to confirm that this is accepted as an enhancement?

Secondly, is there a way for now, to work around this so that the aardvark DNS talks to configured resolver inside the container? From the snippet that @Luap99 posted above, looks like this is not possible. Still being hopeful and asking the question.

Thank you

**Comment by Luap99** [comment]
> Is it possible to confirm that this is accepted as an enhancement?

Yes that is something we want to fix for sure. I don't think there is a workaround.

**Comment by dshenai** [comment]
One more question related to this:
So currently, when the aardvark DNS refers to the host's /etc/resolv.conf, if that file has multiple nameserver entries, will it try to resolve the name by sending the query to all of them one by one?

(https://github.com/containers/aardvark-dns/blob/d77ecad2a9ca4ca8ad66d380f702928869882d87/src/dns/coredns.rs#L307)

It does not seem to work for me. It only refers to the first DNS in my host's /etc/resolv.conf always.
Following is my sample /etc/resolv.conf

`search sample.domain1.com domain2.com
nameserver    1.1.1.1
nameserver    2.2.2.2
`
Both the nameservers are reachable from host. fqdn1 belongs to nameserver1 and fqdn2 belongs to nameserver2. From container, I can nslookup only fqdn1 and not fqdn2.

Could you please help understand if I am expecting correct thing? Or will it refer to only the first DNS in host's resolv.conf?

Thank you

**Comment by M1cha** [comment]
It'd also be great if we could completely disable using any DNS servers at all. Most of my containers don't have internet accesses (nftables firewall). Having aardvark forward requests to a DNS server in the internet allows for DNS tunneling attacks.

To make this useful this should be configurable per container though - either by having podman run multiple aardvark instances or by making aardvark aware where the request is coming from.

**Comment by Luap99** [comment]
This was fixed a while back in #240 AFAIK, so closing this.

**Comment by dshenai** [comment]
Hi 
There is slight mismatch here.
On a host how DNS resolution works: contents of resolve.conf are referred. If I update resolve.conf, I do not have to restart the host. It is plug and play.
On container with Netavark how the resolution will work as per #240: Every time I have to change the DNS, I need to restart the container.  Could we not have plug and play here also?
Thank you

**Comment by flouthoc** [comment]
@dshenai Now `podman` allows to add custom resolvers at network level and they can be updated without restarting the container. Check https://docs.podman.io/en/latest/markdown/podman-network-update.1.html I think this should help you if i understood your problem correctly.

**Comment by dshenai** [comment]
Thanks @flouthoc. That link proved helpful.
