### ISSUE TITLE
Add LICENSE file and COC to repoistory

### ISSUE THREAD

**Issue by sdake** [containers/aardvark-dns#279]
Hello,

I noticed that your project has a ASL2 license as per `Cargo.toml` although there is no LICENSE file in the repository.

There also doesn't appear to be a code of conduct, or other standard documentation.

Thank you,
-steve

**Comment by Luap99** [comment]
LICENSE file is included since the first commit in this repo: https://github.com/containers/aardvark-dns/blob/main/LICENSE

As for the CoC the general containers one applies: https://github.com/containers/common/blob/main/CODE-OF-CONDUCT.md
We properly should add a link in the repo for that.
