### ISSUE TITLE
Updating trust-dns

### ISSUE THREAD

**Issue by plugwash** [containers/aardvark-dns#380]
We would like to get rid of the rust-webpki package in Debian as it's abandoned upstream and has a security issue. One of the blockers for doing so is updating the trust-dns-* crates.

Your package uses some of the trust-dns crates, though it doesn't appear to use the features that depend on webpki. Still it would be be preferable to get it up to date. I see a bot has already bumped the dependency on trust-dns-server, but has left the dependencies on trust-dns-client and trust-dns-proto alone. This seems suboptimal to say the least as it means your builds now include two different versions of trust-dns-proto.

After bumping the dependency I get a bunch of errors like

    error[E0308]: mismatched types
       --> src/dns/coredns.rs:224:83
        |
    224 | ...                   .set_data(Some(RData::PTR(answer)))
       |                                      ---------- ^^^^^^ expected struct `trust_dns_client::rr::rdata::PTR`, found struct `Name`
       |                                      |
       |                                      arguments to this enum variant are incorrect
       |
    note: tuple variant defined here
      --> /<redacted>/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.23.0/src/rr/record_data.rs:481:5  
        |
    481 |     PTR(PTR),
        |     ^^^
    help: try wrapping the expression in `trust_dns_client::rr::rdata::PTR`
        |
    224 |                                                         .set_data(Some(RData::PTR(trust_dns_client::rr::rdata::PTR(answer))))
        |                                                                                   +++++++++++++++++++++++++++++++++      +

These seem to be able to be fixed by following the suggestion in the error message.

However I also get another error.

    error[E0596]: cannot borrow data in dereference of `DnsResponse` as mutable
       --> src/dns/coredns.rs:431:13
        |
    431 |             response.set_id(id);
        |             ^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
        |
        = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `DnsResponse`

Which I have no clue how to fix.

**Comment by flouthoc** [comment]
@plugwash I am checking it thanks.
