### ISSUE TITLE
DNS requests timeout

### ISSUE THREAD

**Issue by matejzero** [containers/aardvark-dns#389]
I am using podman as a docker replacement on our gitlab-runner host. I have a 40 containers concurrency limit and when I start my tests, I get DNS resolution errors.

Testing environment:
- 16 vCPUs
- 24GB memory
- CentOS 9 stream
- podman 4.6.1-5.
- slirp4netns: slirp4netns-1.2.2-1.el9.x86_64
- aardvark-dns: aardvark-dns-1.7.0-1.el9

While running tests, I get random dns resolution fail errors inside containers (actual host replaced with host.example.tld):
```
Example 1:
Cloning into 'spec/fixtures/modules/yumrepo_core'...
ssh: Could not resolve hostname host.example.tld: Temporary failure in name resolution
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Example 2:
$ bundle install -j $(nproc)
Fetching gem metadata from https://host.example.tld/nexus/repository/GroupRubyGems/..
Fetching gem metadata from https://host.example.tld/nexus/repository/GroupRubyGems/..
Could not find gem 'beaker (~> 5)' in any of the gem sources listed in your

Example 3:
Initialized empty Git repository in /builds/puppet/freeradius/.git/
Created fresh repository.
fatal: unable to access 'https://host.example.tld/puppet/freeradius.git/': Could not resolve host: host.example.tld
Cleaning up project directory and file based variables
```

This does not happen in every container, it's sporadic and random. If I switch back to `cni` backend, it works without errors.

I tried running up to 8 containers and flooding the dns server with dns lookups, but I could not get a DNS resolution error. Will try to ramp that up to 30-40 and see if I can reproduce.

If anyone has an idea how to debug this, I will gladly look into it if my knowledge allows me.

**Comment by matejzero** [comment]
This is only for public domain names, I don't use any container names in my tests. 

I managed to setup journald logging and the only error I saw was  `aardvark-dns[129509]: [25183] fail response: ProtoError { kind: Msg("mpsc::SendError send failed because receiver is gone") }`

Apart from that, there is a lot of `Received SIGHUP will refresh servers: 1`. That is probably because I run 40 containers which are spawning up and down fast (my tests last between 20s and 2min).

Sometimes I also see:
```
aardvark-dns[129509]: No configuration found stopping the sever
systemd[1084]: Started /usr/libexec/podman/aardvark-dns --config /run/user/988/containers/networks/aardvark-dns -p 53 run.
```

Example of logs:
```
Sep 29 12:11:26 host.example.tld aardvark-dns[72066]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:27 host.example.tld aardvark-dns[72066]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:27 host.example.tld aardvark-dns[72066]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:28 host.example.tld aardvark-dns[72066]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:28 host.example.tld aardvark-dns[72066]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:28 host.example.tld aardvark-dns[72066]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:29 host.example.tld aardvark-dns[72066]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:30 host.example.tld aardvark-dns[72066]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:32 host.example.tld aardvark-dns[72066]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:32 host.example.tld aardvark-dns[72066]: No configuration found stopping the sever
Sep 29 12:11:33 host.example.tld systemd[1084]: Started /usr/libexec/podman/aardvark-dns --config /run/user/988/containers/networks/aardvark-dns -p 53 run.
Sep 29 12:11:34 host.example.tld aardvark-dns[84196]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:34 host.example.tld aardvark-dns[84196]: No configuration found stopping the sever
Sep 29 12:11:39 host.example.tld systemd[1084]: Started /usr/libexec/podman/aardvark-dns --config /run/user/988/containers/networks/aardvark-dns -p 53 run.
Sep 29 12:11:40 host.example.tld aardvark-dns[84336]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:41 host.example.tld aardvark-dns[84336]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:41 host.example.tld aardvark-dns[84336]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:41 host.example.tld aardvark-dns[84336]: No configuration found stopping the sever
Sep 29 12:11:41 host.example.tld systemd[1084]: Started /usr/libexec/podman/aardvark-dns --config /run/user/988/containers/networks/aardvark-dns -p 53 run.
Sep 29 12:11:41 host.example.tld aardvark-dns[84649]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:42 host.example.tld aardvark-dns[84649]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:42 host.example.tld aardvark-dns[84649]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:43 host.example.tld aardvark-dns[84649]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:43 host.example.tld aardvark-dns[84649]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:43 host.example.tld aardvark-dns[84649]: No configuration found stopping the sever
Sep 29 12:11:44 host.example.tld systemd[1084]: Started /usr/libexec/podman/aardvark-dns --config /run/user/988/containers/networks/aardvark-dns -p 53 run.
Sep 29 12:11:45 host.example.tld aardvark-dns[85160]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:45 host.example.tld aardvark-dns[85160]: No configuration found stopping the sever
Sep 29 12:11:46 host.example.tld systemd[1084]: Started /usr/libexec/podman/aardvark-dns --config /run/user/988/containers/networks/aardvark-dns -p 53 run.
Sep 29 12:11:48 host.example.tld aardvark-dns[85294]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:48 host.example.tld aardvark-dns[85294]: No configuration found stopping the sever
Sep 29 12:11:49 host.example.tld systemd[1084]: Started /usr/libexec/podman/aardvark-dns --config /run/user/988/containers/networks/aardvark-dns -p 53 run.
Sep 29 12:11:49 host.example.tld aardvark-dns[85439]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:50 host.example.tld aardvark-dns[85439]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:50 host.example.tld aardvark-dns[85439]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:51 host.example.tld aardvark-dns[85439]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:51 host.example.tld aardvark-dns[85439]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:51 host.example.tld aardvark-dns[85439]: No configuration found stopping the sever
Sep 29 12:11:51 host.example.tld systemd[1084]: Started /usr/libexec/podman/aardvark-dns --config /run/user/988/containers/networks/aardvark-dns -p 53 run.
Sep 29 12:11:51 host.example.tld aardvark-dns[85951]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:52 host.example.tld aardvark-dns[85951]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:52 host.example.tld aardvark-dns[85951]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:52 host.example.tld aardvark-dns[85951]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:53 host.example.tld aardvark-dns[85951]: Received SIGHUP will refresh servers: 1
Sep 29 12:11:53 host.example.tld aardvark-dns[85951]: Received SIGHUP will refresh servers: 1
```

**Comment by Luap99** [comment]
> No configuration found stopping the sever

This is normal assuming all containers are stopped at that moment. The next container start would respawn the process. 




> As far as errors goes, there were 2:
> 
>     * `aardvark-dns[129509]: [25183] fail response: ProtoError { kind: Msg("mpsc::SendError send failed because receiver is gone") }`
> 
>     * `aardvark-dns[215345]: 14284 dns request got empty response`

These look definitely relevant, @flouthoc any idea?

**Comment by matejzero** [comment]
The problem is that our of 150 containers, between 10 and 20 fail due to dns error. Could SIGHUPs be the reason if the request comes when server is reloading?

**Comment by Luap99** [comment]
That is a possibility, are these containers all on the same network or are there multiple networks in use?

**Comment by matejzero** [comment]
Every container is in it's own network (I'm using FF_NETWORK_PER_BUILD flag with gitlab-runner).

**Comment by flouthoc** [comment]
Would it be possible run `aardvark-dns` in debug mode and share logs ?

**Comment by matejzero** [comment]
I think I could, yes. How do I run aardvark in debug mode?

**Comment by flouthoc** [comment]
@Luap99 Does `--log-level` gets propogated to `aardvark-dns` and `netavark` ?

**Comment by Luap99** [comment]
Yes `podman --log-level debug ...` gets passed down to netavark and aardvark. Although it is important to keep in mind that this of course has to happen on the command that start the aardvark-dns server, so it must be set on the first podman command who starts a container with dns.

**Comment by Luap99** [comment]
Anyway the code looks pretty clear to me we teardown on each sighub and the setup again, that definitely looks wrong and likely is responsible for the package loss. We must keep the sockets active only only add/remove the ones according to the changed configs. Looking at it this whole section would need to be rewritten to handle it in a much better way.

**Comment by matejzero** [comment]
I have to figure our a way to do that with gitlab-runner if it's even possible. I wasn't able to replicate this issue without gitlab-runner jobs.

**Comment by Luap99** [comment]
I would assume just spamming the aardvark-dns process with SIGHUB signals should work as a reproducer to cause some package loss as the sockets are closed and opened each time again. So it is just a question of hitting that window.

**Comment by matejzero** [comment]
I was hoping to have some more time to debug this, but unfortunately I had to switch back to docker for performance reasons so no new info from my side:/

**Comment by Luap99** [comment]
https://github.com/containers/aardvark-dns/issues/389#issuecomment-1746368749 is still valid and must be fixed, and seeing all the `Received SIGHUP will refresh servers` messages makes me confident that this is the problem you are seeing.

**Comment by JKHSDTV** [comment]
Same issue seen by us; we use containers to run medium lived batch jobs (~5-15 minutes with 5 minute pauses), and multiple restarting containers result in many reported failures to resolve URLs via aardvark. It got so bad that we "solved" this by mounting in a read-only `/etc/resolv.conf`. This left us unable to resolve other container names, but in this use case, that is an acceptable compromise. No other approach to mitigate this issue has worked for us.

**Comment by Luap99** [comment]
> No other approach to mitigate this issue has worked for us.

If you do not wish to use aardvark-dns you could just create the podman networks with `--disable-dns`

**Comment by crispytaco** [comment]
I believe I have the same issue.

I come from docker compose and have built a habit of putting each app in it's own private network.

In my case, if I only attach one container to the network I've created, public dns resolution does not work; however, as soon as I connect a second container public dns works.  It continues to work, even if I remove the second container. 

If I stop all containers using that network, the process starts over, public dns resolution stops working until I add another container.

**Comment by Luap99** [comment]
> I believe I have the same issue.
> 
> I come from docker compose and have built a habit of putting each app in it's own private network.
> 
> In my case, if I only attach one container to the network I've created, public dns resolution does not work; however, as soon as I connect a second container public dns works. It continues to work, even if I remove the second container.
> 
> If I stop all containers using that network, the process starts over, public dns resolution stops working until I add another container.

This does not sound related, this is clearly a different bug. If you have a proper reproducer please file a new bug.

**Comment by robhancocksed** [comment]
We have been hit by this issue as well using Podman with GitLab CI containers. It seems that even when using the FF_NETWORK_PER_BUILD flag in GitLab CI to use a separate network between containers, a single aardvark-dns process ends up being used and experiences this issue.

**Comment by Luap99** [comment]
You are welcome to submit a fix according to my comments above, I simply have no time to implement this right now.

**Comment by svenstaro** [comment]
Ok. We'll look into it.

**Comment by seanlafferty-ibm** [comment]
I didn't catch any aardvark logs, but via journald I confirmed the dns failure happened precisely when one container was killed (line 1 runner 23 is killed, and at the last line runner-28 fails on dns). This is all within the same second.

```
Mar 25 13:02:02 s1gitrunrtp3 runner-23[1061284]: Exiting runner...
Mar 25 13:02:02 s1gitrunrtp3 podman[1417763]: 2025-03-25 13:02:02.583260026 -0400 EDT m=+0.082448310 container died e7f1c539a70b77a5cfcdcd1c8175eae16d39086797b85dae3f1791481605bf80 (image=localhost/podman-runner:lates>
Mar 25 13:02:02 s1gitrunrtp3 avahi-daemon[594403]: Interface veth263.IPv6 no longer relevant for mDNS.
Mar 25 13:02:02 s1gitrunrtp3 avahi-daemon[594403]: Leaving mDNS multicast group on interface veth263.IPv6 with address fe80::b4c5:d4ff:fe9a:ec69.
Mar 25 13:02:02 s1gitrunrtp3 kernel: podman1: port 116(veth263) entered disabled state
Mar 25 13:02:02 s1gitrunrtp3 kernel: device veth263 left promiscuous mode
Mar 25 13:02:02 s1gitrunrtp3 kernel: podman1: port 116(veth263) entered disabled state
Mar 25 13:02:02 s1gitrunrtp3 avahi-daemon[594403]: Withdrawing address record for fe80::b4c5:d4ff:fe9a:ec69 on veth263.
Mar 25 13:02:02 s1gitrunrtp3 gnome-shell[2465]: Removing a network device that was not added
Mar 25 13:02:02 s1gitrunrtp3 systemd[1]: run-netns-netns\x2d359de7a8\x2da773\x2d1899\x2d9360\x2da90934525533.mount: Deactivated successfully.
Mar 25 13:02:02 s1gitrunrtp3 systemd[1]: var-lib-containers-storage-overlay\x2dcontainers-e7f1c539a70b77a5cfcdcd1c8175eae16d39086797b85dae3f1791481605bf80-userdata-shm.mount: Deactivated successfully.
Mar 25 13:02:02 s1gitrunrtp3 systemd[1]: var-lib-containers-storage-overlay-f3578e7c712371891b04e8e26126656c6a9f8e7cac00e4bf42f13ad3802390f8-merged.mount: Deactivated successfully.
Mar 25 13:02:02 s1gitrunrtp3 podman[1417763]: 2025-03-25 13:02:02.938996954 -0400 EDT m=+0.438185241 container remove e7f1c539a70b77a5cfcdcd1c8175eae16d39086797b85dae3f1791481605bf80 (image=localhost/podman-runner:lat>
Mar 25 13:02:02 s1gitrunrtp3 runner-28[1206189]: [WORKER 2025-03-25 17:02:02Z INFO StepsRunner] Step result: Failed
```

**Comment by matejzero** [comment]
We just switched to podman 5.2.2 on our CI servers and we didn't get any errors. We had at most 20 containers running, but they were short lived so there was a lot of new ones spawning all the time.

**Comment by Luap99** [comment]
@seanlafferty-ibm Are you starting/stopping all containers on a single network? If all containers on the network are stopped we still have to remove the listener and then when the next one is started add it again.

The SIGHUP API is not reliable as it is not race free. By the time we removed the listener we might already have a new container setup that again used dns. What we need is a proper bidirectional API https://github.com/containers/aardvark-dns/issues/338

So overall I can only see things failing if a new container is spawned on the network which has no active listener. On a long running container I would not expect any dns failures generally.

Of course there could still be other errors, netavark might have not written the right config file. ardvark-dns didn't parse it correctly or ignored some listening error...

Without simple reproducers it is always hard to tell.

In any case I suggest you file a new issue as this is closed for a while now.
