### ISSUE TITLE
Is there a way to reserve or limit IP addresses when using DNS?

### ISSUE THREAD

**Issue by dmocek** [containers/aardvark-dns#392]
We have a requirement to have both static and dynamic IP addresses when our containers are run.  We'd like to limit the dynamic IP addresses to a range so the static IP addresses aren't assigned to the dynamic IP address containers if the dynamic containers are run before the static ones.

**Comment by Luap99** [comment]
This is not a aardvark issue, aardvark-dns just serves names for ips of the container, it has no control over ip assignments.

Anyway sounds like you want to use the `--ip-range` option on `podman network create`
