### ISSUE TITLE
Can't resolve from outside of containers.

### ISSUE THREAD

**Issue by bwskin** [containers/aardvark-dns#508]
With version 1.12.0 I can't get results from aardvark-dns directly from host system. Downgrade to 1.11.0 fixes it. It works correctly when accessing from container.

With v1.11.0:
```sh
~> nslookup gitea 172.20.0.1
Server:		172.20.0.1
Address:	172.20.0.1#53

Non-authoritative answer:
Name:	gitea
Address: 172.20.0.8
```
With v1.12.2, same config:
```
> nslookup gitea 172.20.0.1
Server:		172.20.0.1
Address:	172.20.0.1#53

** server can't find gitea: NXDOMAIN
```
Is that expected behaviour now? Or is it configurable (using podman config)?

**Comment by Luap99** [comment]
We generally never really considered/supported the use case of resolving the names from the host directly.

I think I "broke" this in my rework (not intentionally) so if it worked before we can add it back if it is useful

**Comment by bwskin** [comment]
It's useful for me, for example with ssh passing through to gitea. I just had aardvark-dns as additional resolver for some names in dnsmasq. Host can get ip address of the container to connect, and I don't have to maintain static ip for every service container i have. Pretty convenient to have it.
